C_SRC += $(DRIVERS)/Src/stm32f1xx_hal.c
C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_rcc.c
# C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_dac.c
# C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_i2c.c
# C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_i2c_ex.c
C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_dma.c
# C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_dma_ex.c
C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_gpio.c
# C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_adc.c
# C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_adc_ex.c
# C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_pwr_ex.c
# C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_rcc_ex.c
# C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_flash_ex.c
C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_tim_ex.c
C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_tim.c
C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_cortex.c
# C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_sai.c
# C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_sai_ex.c
# C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_rng.c
# C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_qspi.c
C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_uart.c
C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_spi.c
# C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_dma2d.c
# C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_hcd.c
# C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_pcd.c # USB Device
# C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_pcd_ex.c
# C_SRC += $(DRIVERS)/Src/stm32f1xx_hal_sdram.c
# C_SRC += $(DRIVERS)/Src/stm32f1xx_ll_usb.c
# C_SRC += $(DRIVERS)/Src/stm32f1xx_ll_fmc.c

# C_SRC += $(BUILD)/startup.c
# C_SRC += $(BUILD)/libnosys_gnu.c
# C_SRC += $(USB_DEVICE) $(USB_OTG)
# C_SRC += $(DSPLIB)/FastMathFunctions/arm_sin_f32.c
# C_SRC += $(DSPLIB)/FastMathFunctions/arm_cos_f32.c
# C_SRC += $(DSPLIB)/CommonTables/arm_common_tables.c

# C_SRC += $(DSPLIB)/TransformFunctions/arm_cfft_f32.c
# C_SRC += $(DSPLIB)/TransformFunctions/arm_cfft_radix8_f32.c
# C_SRC += $(DSPLIB)/TransformFunctions/arm_bitreversal2.c
# C_SRC += $(DSPLIB)/TransformFunctions/arm_rfft_fast_f32.c
# C_SRC += $(DSPLIB)/TransformFunctions/arm_rfft_fast_init_f32.c
# C_SRC += $(DSPLIB)/CommonTables/arm_const_structs.c

# C_SRC += $(DSPLIB)/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c
# C_SRC += $(DSPLIB)/FilteringFunctions/arm_biquad_cascade_df1_f32.c

# C_SRC += $(DSPLIB)/SupportFunctions/arm_copy_f32.c
# C_SRC += $(DSPLIB)/SupportFunctions/arm_float_to_q31.c
# C_SRC += $(DSPLIB)/SupportFunctions/arm_q31_to_float.c
# C_SRC += $(DSPLIB)/SupportFunctions/arm_float_to_q15.c
# C_SRC += $(DSPLIB)/SupportFunctions/arm_q15_to_float.c

# C_SRC += $(DSPLIB)/FastMathFunctions/arm_sin_f32.c
# C_SRC += $(DSPLIB)/FastMathFunctions/arm_cos_f32.c
# C_SRC += $(DSPLIB)/FilteringFunctions/arm_biquad_cascade_df1_f32.c
# C_SRC += $(DSPLIB)/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c
# C_SRC += $(DSPLIB)/SupportFunctions/arm_float_to_q31.c
# C_SRC += $(DSPLIB)/SupportFunctions/arm_q31_to_float.c
# C_SRC += $(DSPLIB)/SupportFunctions/arm_float_to_q15.c
# C_SRC += $(DSPLIB)/SupportFunctions/arm_q15_to_float.c
