#define OWL_PEDAL_HARDWARE          0x11
#define OWL_MODULAR_HARDWARE        0x12
#define OWL_RACK_HARDWARE           0x13
#define PRISM_HARDWARE              0x14
#define PLAYER_HARDWARE             0x15
#define TESSERACT_HARDWARE          0x16
#define ALCHEMIST_HARDWARE          0x17
#define WIZARD_HARDWARE             0x18
#define MAGUS_HARDWARE              0x19
#define EFFECTSBOX_HARDWARE         0x1a
#define WAVETABLE_HARDWARE          0x1b
#define NOCTUA_HARDWARE             0x1c
#define BIOSIGNALS_HARDWARE         0x1d
#define LICH_HARDWARE               0x1e
#define WITCH_HARDWARE              0x1f
